<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFNy1bLJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFNy1bLJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFNy1bLJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFNy1bLJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFNy1bLJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FNy1bLJ',
    'container.build_id' => '792ed923',
    'container.build_time' => 1607946591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFNy1bLJ');
