<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtt0G6c\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtt0G6c/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPtt0G6c.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPtt0G6c\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPtt0G6c\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ptt0G6c',
    'container.build_id' => '0bda666c',
    'container.build_time' => 1607929234,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtt0G6c');
